[tools]
node = "26.7.0"
rust = "1.97.1"
superhtml = "0.7.0"
watchexec = "2.5.1"

[tasks.export]
run = "cargo run"

[tasks.watch]
run = "watchexec -w posts -w src -- mise export && npx prettier --write site/*.html"